### ISSUE TITLE
Upload to Brackets extension registry (or deprecate)

### ISSUE THREAD

**Issue by njx** [WebsiteDeveloper/GitHubAccess#1]
Hey there--I'm going through the old Brackets Extensions wiki page (https://github.com/adobe/brackets/wiki/Brackets-Extensions) and noticed that you hadn't uploaded this extension to the registry yet, so this is a nudge :) If you don't think it makes sense to keep this extension around, could you move it to the "Deprecated Extensions" section of the wiki page? Thanks.

**Comment by WebsiteDeveloper** [comment]
@njx i'm going to add it in a couple of days^ im currently trying to add binary data support. if thats finished i will definitly upload the extension. But anyway thanks for the reminder.

**Comment by WebsiteDeveloper** [comment]
Finally Done.

**Comment by njx** [comment]
Great, thanks!
