### ISSUE TITLE
Will not work in Brackets Sprint 34

### ISSUE THREAD

**Issue by peterflynn** [WebsiteDeveloper/GitHubAccess#2]
This extension uses several APIs which have been removed.  In the next release of Brackets, the extension will crash.

The APIs are:
- `DirectoryEntry.getFile()` with `create: true`
- `DirectoryEntry.getDirectory()` with`create: true`

It should be straightforward to switch to the new APIs based on the [API migration guide](https://github.com/adobe/brackets/wiki/File-System-API-Migration).  You can release this update in advance if you want, since users of Brackets Sprint 33 (the current release) will still be able to install the older version of your extension that is compatible with their build.

See [this discussion thread](https://groups.google.com/forum/#!topic/brackets-dev/95PyDKfMO0M) for info about the reason for the API changes.

**Comment by peterflynn** [comment]
Correction to what I said above: `FileEntry.createWriter()` is merely deprecated and should not break right away (though there's no reason to hold off on making those changes at the same time).

**Comment by peterflynn** [comment]
More info on deprecations...  There are several uses of deprecated APIs in this extension:
- `NativeFileSystem.showOpenDialog()`
- `NativeFileSystem.requestNativeFileSystem()`
- `FileEntry.createWriter()`

These APIs _should_ continue to work in Brackets Sprint 34, so you do not necessarily need to clean them up at the same time as fixing the breaking changes above.  But the APIs will go away by the end of this year, so you should migrate away from them as soon as you have time (see same [migration guide](https://github.com/adobe/brackets/wiki/File-System-API-Migration) as above).

Let me know if you want me to spin that off as a separate issue or anything.

**Comment by WebsiteDeveloper** [comment]
Will be fixed once i release 0.2

**Comment by WebsiteDeveloper** [comment]
Fixed now
