### ISSUE TITLE
Node process not finding es6-promise

### ISSUE THREAD

**Issue by anephew** [WebsiteDeveloper/GitHubAccess#3]
Hello! After installation and generated token I'm trying to try the extension but without results. "Clone Repository" button innactive, in general, nothing works. Please help me.

![screenshot-startpage 2014-06-04 08-51-57](https://cloud.githubusercontent.com/assets/551514/3169706/218432d0-eba4-11e3-9e42-1692c1666a59.png)

39 build, windows 7 x64

thanks

**Comment by anephew** [comment]
Developer Tools - Console:

[NodeDomain] Error loading domain "github-access": Unable to load one of the modules: C:/Users/anephew/AppData/Roaming/Brackets/extensions/user/bsirlinger.github-access/node/GitHubAccessDomain, reason: Cannot find module 'es6-promise'

**Comment by WebsiteDeveloper** [comment]
@anephew i uploaded a new version. Could you please try this out?

**Comment by anephew** [comment]
Yes. Same issue and error in console. And after click on "Get branches..." new error:

![github](https://cloud.githubusercontent.com/assets/551514/3171289/b1b3d5f2-ebc4-11e3-96b4-3111e3dc2efd.png)

**Comment by WebsiteDeveloper** [comment]
You have to fill in "User/Repository" so for example "WebsiteDeveloper/GitHubAccess".

**Comment by anephew** [comment]
Hmm ok, but nothing happens after i get braches for Repository, choose folder and hit the Clone button. The window closes and the files are not downloaded, the folder I chose is empty.

It would be nice to make download by the direct link to .git and take the current directory of the open project by default to download there.
I realized now that generally easier to download the repository in zip from the Repository page in browser. 

thank you

**Comment by WebsiteDeveloper** [comment]
It seems that nothing happens, because there is an error inside the node process.
As to the other things, what do you mean by direct link to .git? Something like this https://github.com/WebsiteDeveloper/GitHubAccess ?
And defaulting the directory to the current project directory is a good idea by the way, so thanks for that.

**Comment by anephew** [comment]
"As to the other things, what do you mean by direct link to .git? "

![git](https://cloud.githubusercontent.com/assets/551514/3174677/1734cef2-ebf4-11e3-8d77-f5b89c8a9647.png)

And for example it can be a direct link to zip. In general, the main thing that you could provide a link to the repository and click the "clone", without unnecessary movements in brackets. Otherwise faster download repository directly from its pages.

Check popular Bracket Git extension https://github.com/zaggino/brackets-git, it provides Git integration for Brackets, and i like "Clone" feature there in few clicks In an empty folder of your project

![git1](https://cloud.githubusercontent.com/assets/551514/3174732/98b0a7e4-ebf4-11e3-9d90-cce2d2ef5790.png)

**Comment by WebsiteDeveloper** [comment]
@anephew i uploaded a new version which should fix the console error and the error with not writing anything to disk.
Could you please verify, and then close this issue?
